### ISSUE TITLE
Issue with some functions 

### ISSUE THREAD

**Issue by QuangDucc** [PengchengShi1220/NexToU#6]
Hello,

Thank you for providing code.

I tried to reproduce your base model but I get some errors. If I use CPU to predict a sample, it works but the problem occurred when I use GPU.

1) function batched_index_select raised an error is out of index while selecting index for features
2) function torch.topk got error CUDA error: an illegal memory access was encountered

Did you get this errors before. Could you kindly provide on how to fix this?

Thank you for your assistance.

Best regards.

**Comment by PengchengShi1220** [comment]
Hi @QuangDucc ,

Thank you for reaching out and for the detailed description of your issue.

The "out of index" error typically indicates a mismatch in tensor sizes between CPU and GPU operations. The CUDA memory access error often suggests issues with memory allocation or type mismatches between CPU and GPU tensors.

To assist you further, could you please provide the complete error logs?

Looking forward to helping you resolve this issue.

Best,
Pengcheng

**Comment by QuangDucc** [comment]
Thank you for your clarify. I fixed it.

I have one more question. I custom the encoder with this config:
        strides = [[1,1,1],[1,1,1],[2,2,2],[2,2,2],[2,2,2],[2,2,2]]
        conv_kernel_sizes = [[1,1,1],[3,3,3],[3,3,3],[3,3,3],[3,3,3],[3,3,3]]
        input_channels=3, 
        patch_size=(64,64,64), 
        n_stages = 6,
        features_per_stage=[48,48,24,24,24,24], 
        conv_op=nn.Conv3d, 
        kernel_sizes=conv_kernel_sizes, 
        strides=strides, 
        n_conv_per_stage=[2,2,2,2,2,2], 
        norm_op=nn.BatchNorm3d, 
        norm_op_kwargs={'eps': 1e-05, 'affine': True})

But when I summary model, I get this result
![Screenshot 2024-02-22 at 10 33 04 AM](https://github.com/PengchengShi1220/NexToU/assets/96943341/e6117e70-317f-454a-91d8-f68b2de2d946)
It looks like just the first 2 stages (include 2 stacks convolution) are trained, the others (include conv+graph) are not. I checked the code but still cannot clarify why this happened. Could you assist me?. Thanks in advance

**Comment by QuangDucc** [comment]
I found it. Just set requires_grad=True in the relative_pos, the default value is False.

**Comment by PengchengShi1220** [comment]
Hi,

The `self.relative_pos` parameter in [torch_vertex.py](https://github.com/huawei-noah/Efficient-AI-Backbones/blob/4fd7598cb2ade9cc410832dff99814bfff6f390c/vig_pytorch/gcn_lib/torch_vertex.py#L161) is set with `requires_grad=False` as it's not intended for training. It's used to add relative position values in distance computation (see [torch_edge.py](https://github.com/huawei-noah/Efficient-AI-Backbones/blob/4fd7598cb2ade9cc410832dff99814bfff6f390c/vig_pytorch/gcn_lib/torch_edge.py#L75)). Changing `requires_grad` to `True` for this parameter is not recommended.

Regarding the `features_per_stage` configuration, the values `[48,48,24,24,24,24]` might be too small for larger stages. Typically, the number of channels increases with each stage, as seen in the BTCV dataset settings `[24,48,96,192,312,312]`. 
For a better understanding, here’s a summary example and a model summary from the BTCV dataset:

```python
model = self.network.cuda()
from torchsummary import summary
if self.threeD:
    h, w, d = self.patch_size
    summary(model, (self.num_input_channels, h, w, d))
else:
    h, w = self.patch_size
    summary(model, (self.num_input_channels, h, w))
```
[NexToU_nnunetv1_BTCV_48_192_192_model_summary.txt](https://github.com/PengchengShi1220/NexToU/files/14370428/NexToU_nnunetv1_BTCV_48_192_192_model_summary.txt)

I hope this helps. If you have more questions, feel free to ask.

**Comment by QuangDucc** [comment]
Thank you for your clarification.
